# Exercise 1: 
# Create the following arrays:
# 1. A 1D array of numbers from 0 to 9
# 2. A 2D array of shape (3, 4) filled with zeros
# 3. A 3x3 identity matrix
# 4. A 1D array of 10 equally spaced values between 1 and 100
# 5. A 3x3 array with random integers between 10 and 50
# Print all arrays

In [5]:
import numpy as np

# 1. 1D array from 0 to 9
arr1 = np.arange(10)

# 2. 2D array (3x4) filled with zeros
arr2 = np.zeros((3, 4))

# 3. 3x3 identity matrix
arr3 = np.eye(3)

# 4. 1D array with 10 equally spaced values between 1 and 100
arr4 = np.linspace(1, 100, 10)

# 5. 3x3 array with random integers between 10 and 50
arr5 = np.random.randint(10, 51, (2,3,3))

# Print all arrays
print("1D array (0 to 9):\n", arr1)
print("\n2D zeros array (3x4):\n", arr2)
print("\n3x3 Identity matrix:\n", arr3)
print("\nEqually spaced values (1 to 100):\n", arr4)
print("\nRandom integers (10 to 50):\n", arr5)

1D array (0 to 9):
 [0 1 2 3 4 5 6 7 8 9]

2D zeros array (3x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

3x3 Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Equally spaced values (1 to 100):
 [  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]

Random integers (10 to 50):
 [[[24 24 49]
  [14 17 41]
  [18 50 20]]

 [[17 19 29]
  [33 14 17]
  [11 15 15]]]


# Exercise 2: 
# Create a 3D array with shape (2, 3, 4) using random numbers
# Find and print:
# - Number of dimensions
# - Shape of the array
# - Total number of elements
# - Data type of elements
# - Size in bytes of each element
# - Total memory consumed by the array

In [7]:
import numpy as np

# Create a 3D array with shape (2, 3, 4) using random numbers
arr_3d = np.random.randint(0, 10, (2, 3, 4))
arr = np.array([
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],

    [[10, 11, 12],
     [13, 14, 15],
     [16, 17, 18]]
])
             
print(arr)             

# Find and print the required properties
print("3D Array:")
print(arr_3d)
print("\nNumber of dimensions:", arr_3d.ndim)
print("Shape of the array:", arr_3d.shape)
print("Total number of elements:", arr_3d.size)
print("Data type of elements:", arr_3d.dtype)
print("Size in bytes of each element:", arr_3d.itemsize)
print("Total memory consumed by the array:", arr_3d.nbytes)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
3D Array:
[[[9 5 6 6]
  [5 4 0 9]
  [4 4 7 4]]

 [[0 8 5 4]
  [5 9 3 8]
  [9 9 8 3]]]

Number of dimensions: 3
Shape of the array: (2, 3, 4)
Total number of elements: 24
Data type of elements: int32
Size in bytes of each element: 4
Total memory consumed by the array: 96


# Exercise 3: 
# Create a 1D array of numbers from 1 to 20
# Perform the following operations:
# - Access the first, last, and middle elements
# - Slice the array to get elements from index 5 to 15
# - Get all even numbers using slicing
# - Reverse the array using slicing

In [10]:
import numpy as np

# Create a 1D array of numbers from 1 to 20
arr = np.arange(1, 21)
print("Original array:", arr)

# Access the first, last, and middle elements
first_element = arr[0]
last_element = arr[-1]
middle_element = arr[len(arr) // 2]

print("\nAccessing elements:")
print(f"First element: {first_element}")
print(f"Last element: {last_element}")
print(f"Middle element: {middle_element}")

# Slice the array to get elements from index 5 to 15
sliced_arr = arr[5:15]
print("\nElements from index 5 to 15:", sliced_arr)

# Get all even numbers using slicing
even_numbers = arr[1::2]  # Start from index 1, step by 2 to get even numbers
print("Even numbers:", even_numbers)

# Reverse the array using slicing
reversed_arr = arr[::-1]
print("Reversed array:", reversed_arr)


Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Accessing elements:
First element: 1
Last element: 20
Middle element: 11

Elements from index 5 to 15: [ 6  7  8  9 10 11 12 13 14 15]
Even numbers: [ 2  4  6  8 10 12 14 16 18 20]
Reversed array: [20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


# Exercise 4: 
# Create a 5x5 array with numbers from 1 to 25
# Perform the following tasks:
# - Access the element at row 2, column 3
# - Extract the third row and second column
# - Slice a 3x3 sub-matrix from the center
# - Replace all values in the last row with 0
# - Change the first column to all -1

In [ ]:
import numpy as np

# Create a 5x5 array with numbers from 1 to 25
arr = np.arange(1, 26).reshape(5, 5)
print("Original 5x5 array:\n", arr)

# Access the element at row 2, column 3 (0-based indexing)
element_2_3 = arr[2, 3]
print("\nElement at row 2, column 3:", element_2_3)

# Extract the third row and second column
third_row = arr[2, :]
second_column = arr[:, 1]
print("\nThird row:", third_row)
print("Second column:", second_column)

# Slice a 3x3 sub-matrix from the center
center_submatrix = arr[1:4, 1:4]
print("\nCenter 3x3 sub-matrix:\n", center_submatrix)

# Replace all values in the last row with 0
arr[-1, :] = 0
print("\nArray after replacing last row with 0:\n", arr)

# Change the first column to all -1
arr[:, 0] = -1
print("\nArray after setting first column to -1:\n", arr)


# Exercise 5: 
# Create a 1D array of 15 random integers between 1 and 50
# Perform the following:
# - Select elements at indices [1, 3, 5, 7]
# - Find all elements greater than 25
# - Replace all values less than 10 with 10
# - Count how many values are between 20 and 40 (inclusive)
# - Extract only the odd numbers from the array

In [ ]:
import numpy as np

# Create a 1D array of 15 random integers between 1 and 50
arr = np.random.randint(1, 51, 15)
print("Original array:", arr)

# Select elements at indices [1, 3, 5, 7]
selected_indices = arr[[1, 3, 5, 7]]
print("\nSelected elements at indices [1, 3, 5, 7]:", selected_indices)

# Find all elements greater than 25
greater_than_25 = arr[arr > 25]
print("\nElements greater than 25:", greater_than_25)

# Replace all values less than 10 with 10
adjusted_arr = arr.copy()
adjusted_arr[adjusted_arr < 10] = 10
print("\nArray after replacing values less than 10 with 10:", adjusted_arr)

# Count how many values are between 20 and 40 (inclusive)
count_20_40 = np.sum((arr >= 20) & (arr <= 40))
print("\nCount of values between 20 and 40 (inclusive):", count_20_40)

# Extract only the odd numbers from the array
odd_numbers = arr[arr % 2 == 1]
print("\nOdd numbers in the array:", odd_numbers)
